### ISSUE TITLE
Allow override on distribution name for Debian-based distros

### ISSUE THREAD

**Issue by martinb3** [jubianchi/hhvm-cookbook#21]
Hello! http://dl.hhvm.com/ubuntu/dists/ contains 'trusty' and 'trusty-lts-3.3' so that you can install the latest or a LTS version of HHVM. Would you be open to my adding an attribute to this cookbook for that value, so that I might override it for my use case?

**Comment by jubianchi** [comment]
Of course :+1:

**Comment by martinb3** [comment]
Let me know if you need anything else from me. Thank you!

**Comment by jubianchi** [comment]
Hi @martinb3!

Sorry for the delay I was busy on other projects. I just merged your PR, thanks for it!

I'm planning a release for the cookbook but I would like to merge #20 before releasing. I'll try to do it as soon as possible.

**Comment by martinb3** [comment]
Cheers, thank you!
